# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c3431715622996f7cc3a3a38d0c0dd38"
name = "test"
handle = "test-13744"
application_url = "https://my-shopyfy-app--development.gadget.app/api/shopify/install-or-render"
embedded = true

[build]
dev_store_url = "quickstart-b7f4dc71.myshopify.com"

[auth]
redirect_urls = [
  "https://my-shopyfy-app--development.gadget.app/api/connections/auth/shopify/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
